### ISSUE TITLE
User shall create entry under any journal

### ISSUE THREAD

**Issue by uvsankar** [uvsankar/dairy#20]
Currently if a user needs to use different journal, he needs to change the journalName in the config. This is tiresome. 
Expose a new endpoint '/journal/{journalName}/new' this is similar to index expect that it wont use the journal name in the config.

**Comment by nithinsanjey** [comment]
why would anyone need 2 journals??

**Comment by uvsankar** [comment]
I had a specific use case. I usually log daily events and occasionally write about any important things  happened. To separate these two I needed this support. 
If needed we can support different templates for each journal which I think will be more interesting.

**Comment by nithinsanjey** [comment]
Yes, everyone has such needs. Good catch!!
