### ISSUE TITLE
Title and heading are hard coded

### ISSUE THREAD

**Issue by nithinsanjey** [uvsankar/dairy#3]
1. Currently the title and heading are hardcoded as 'Sankar's Diary' ;P 
2. Date is fine to show the current date, but should be editable to any date.

**Comment by nithinsanjey** [comment]
@uvsankar 
Is this the correct way of working.. i mean to create issues and then adding them as features. Or is there any correct way of doing this?

**Comment by uvsankar** [comment]
@nithinsanjey  thanks for the interest in this project. Yeah the should be editable. There are two ways of doing this  
 1. Storing it in browser cache itself
 2. Getting all the necessary when initialising the repo for the first time and persisting it in the config.json
Will take it up this weekend.
Yeah this is the correct way of tracking any bugs, improvements , features. When creating an issue please add the corresponding labels.

BTW why should the date be editable ?

**Comment by nithinsanjey** [comment]
@uvsankar The date should be adjustable just in case if the user wishes to write yesterday's entry.
