### ISSUE TITLE
Some very basic PIN like authentication for making and viewing journal entries

### ISSUE THREAD

**Issue by nithinsanjey** [uvsankar/dairy#7]
@uvsankar Do you feel like any basic authentication like PIN or any other thing is needed while viewing entries or making entries.

**Comment by uvsankar** [comment]
@nithinsanjey  This is related to #5 . I'm considering the following approach. The key/PIN should be got from the USER when he opens the webpage for the first time. If the user tries to access a journal with wrong key he wont be able to decrypt it. 
 
  However user can create an entry as long as he enters a key. Which means **to view an entry he should know the key with which he created the entry**.

@nithinsanjey  Please advise if you have any other ideas.

**Comment by Gabrock94** [comment]
Does this means a different key for each entry?

**Comment by uvsankar** [comment]
@Gabrock94  The key is given by the user. So unless he wishes to use a new key to encrypt the entry all the entries created will be encrypted with the same key.
Let me know if you have any suggestions

**Comment by nithinsanjey** [comment]
I was thinking if creating PIN might lead us to complicated thing like forget PIN stuff(and stuff like security questions, maybe). But the thing i really like about this app is that it is simple(minimal), having just the necessary things. We should think with simplicity in mind.

> Simplicity is the ultimate sophistication.

This is exciting!!

**Comment by uvsankar** [comment]
we dont store the PIN anywhere so it is the user's responsibility to remember PIN. To overcome this shortcoming we can send an email(optional) to the users mail account when the user starts the diary app for the first time.We will use the credentials of the user mail account to send the email(sending self email!). We can also provide change key option.

    we can expose these options in the backend itself keeping the UI minimal.

**Comment by Gabrock94** [comment]
> We will use the credentials of the user mail account to send the email(sending self email!)
At least for me this sounds more complicated, because it requires connection with emails as well as an active Internet Connection. But it seems the only way to go.  (At least if you aim to run it as a local software and not an online one)

**Comment by uvsankar** [comment]
For now.. whenever user starts the app he need to enter the password. There is no option for password recovery.
